### ISSUE TITLE
A pause emoji?

### ISSUE THREAD

**Issue by ChenghaoMou** [davestewart/todo-emojis#2]
I would love to see an emoji for paused/on hold entries!

Thanks in advance

**Comment by davestewart** [comment]
Hey man,

Sorry I didn't see this earlier. It's a nice idea!

I edited the icon slightly to make the grey a little lighter, and changed the order of the icons in the docs which I think makes more sense:

![emojis](https://raw.githubusercontent.com/davestewart/todo-emojis/master/docs/emojis.png)

(these look wrong now since #4)

Hopefully people will find use for it.

Cheers,
Dave

**Comment by davestewart** [comment]
Just reopening the issue...

I was reticent to add the pause icon when you first PR'ed as it didn't quite sit right with the analog / written feel of todos; rather than feeling like you could literally draw them, the pause felt more like a button.

I was just about to share the update on Twitter and it struck me - the doing emoji (the dot) should almost be a "play" icon, but doing that really does shift things from analog / human to digital / buttons.

That being said, what if there were two sets icons?

![image](https://user-images.githubusercontent.com/132681/98665958-465a3f80-2344-11eb-9e0a-8a3e11abb430.png)


![image](https://user-images.githubusercontent.com/132681/98665812-0dba6600-2344-11eb-99ea-c5d6283533aa.png)


![image](https://user-images.githubusercontent.com/132681/98666371-d7c9b180-2344-11eb-85f2-50bb329d8c8f.png)

Would be interested to hear your thoughts @ChenghaoMou

**Comment by davestewart** [comment]
Current thinking, maybe a dash of colour; blue, as if "on ice".

![image](https://user-images.githubusercontent.com/132681/98669591-7d7f1f80-2349-11eb-8a03-2e37f72f9bb1.png)

This adds to the original "strike" feeling, as if scribbling through the dot.

Also realised it feels a little like a "progress" bar.
